# Generated by Django 3.2.10 on 2021-12-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_list', to='singerapi.singer')),
            ],
        ),
    ]
